GET http://localhost:3001/api/notes



###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":" hello there"
}


###
POST https://notes-i1sy.onrender.com/api/notes
Content-Type: application/json

{
    "content":" hello there"
}